# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 350)
        MainWindow.setMinimumSize(QtCore.QSize(560, 350))
        MainWindow.setMaximumSize(QtCore.QSize(560, 350))
        MainWindow.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(460, 310, 90, 20))
        self.volume.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"     width: 17px;\n"
"    margin: -5px 0;\n"
"}\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background:rgb(0, 0, 0);;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 9px;\n"
"    width: 17px;\n"
"    margin: -5px 0; \n"
"}")
        self.volume.setTracking(True)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(30, 60, 500, 170))
        self.list.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.list.setObjectName("list")
        self.btn_play_or_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play_or_pause.setGeometry(QtCore.QRect(270, 250, 48, 48))
        self.btn_play_or_pause.setStyleSheet("QPushButton {\n"
"    border-radius: 24px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_play_or_pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btn_play_or_pause.setIcon(icon)
        self.btn_play_or_pause.setIconSize(QtCore.QSize(32, 32))
        self.btn_play_or_pause.setObjectName("btn_play_or_pause")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(160, 255, 40, 40))
        self.btn_back.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/back.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btn_back.setIcon(icon1)
        self.btn_back.setObjectName("btn_back")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(330, 255, 40, 40))
        self.btn_next.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/next.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btn_next.setIcon(icon2)
        self.btn_next.setObjectName("btn_next")
        self.now_time = QtWidgets.QLabel(self.centralwidget)
        self.now_time.setGeometry(QtCore.QRect(15, 310, 50, 20))
        self.now_time.setAlignment(QtCore.Qt.AlignCenter)
        self.now_time.setObjectName("now_time")
        self.full_time = QtWidgets.QLabel(self.centralwidget)
        self.full_time.setGeometry(QtCore.QRect(405, 310, 50, 20))
        self.full_time.setAlignment(QtCore.Qt.AlignCenter)
        self.full_time.setObjectName("full_time")
        self.btn_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_file.setGeometry(QtCore.QRect(420, 10, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_open_file.setFont(font)
        self.btn_open_file.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_open_file.setObjectName("btn_open_file")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(210, 250, 48, 48))
        self.btn_stop.setStyleSheet("QPushButton {\n"
"    border-radius: 24px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_stop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/stop.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.btn_stop.setIcon(icon3)
        self.btn_stop.setIconSize(QtCore.QSize(32, 32))
        self.btn_stop.setObjectName("btn_stop")
        self.running_time = QtWidgets.QSlider(self.centralwidget)
        self.running_time.setGeometry(QtCore.QRect(80, 305, 310, 30))
        self.running_time.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"     width: 17px;\n"
"    margin: -5px 0;\n"
"}\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background:rgb(0, 0, 0);;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 9px;\n"
"    width: 17px;\n"
"    margin: -5px 0; \n"
"}")
        self.running_time.setOrientation(QtCore.Qt.Horizontal)
        self.running_time.setObjectName("running_time")
        self.btn_open_playlist = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_playlist.setGeometry(QtCore.QRect(310, 10, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_open_playlist.setFont(font)
        self.btn_open_playlist.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_open_playlist.setObjectName("btn_open_playlist")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(200, 10, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MP3"))
        self.now_time.setText(_translate("MainWindow", "00:00"))
        self.full_time.setText(_translate("MainWindow", "00:00"))
        self.btn_open_file.setText(_translate("MainWindow", "Open file"))
        self.btn_open_playlist.setText(_translate("MainWindow", "Open playlist"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
